# Generated by Django 5.1.7 on 2025-06-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='tipo',
            field=models.CharField(choices=[('adulto', 'Adulto'), ('nino', 'Nino'), ('estudiante', 'Estudiante'), ('senior', 'Senior'), ('vip', 'VIP')], max_length=50),
        ),
    ]
